### ISSUE TITLE
Problem finding system_wrapper.bit file

### ISSUE THREAD

**Issue by buttercutter** [eliaskousk/parallella-riscv#2]
@eliaskousk , 

I am having problem running the script   ./scripts/build.fpga.bitstream.sh
I understand that you might not have time to check.

> cp: cannot stat './parallella_riscv/system.runs/impl_1/system_wrapper.bit': No such file or directory
make: *** [../scripts/Makefrag:57: /home/promach/Documents/Grive/Personal/Digital/Parallella/parallella-riscv/parallella/fpga/parallella.bit] Error 1

I found similar error when I try to build a helloworld from Parallella OH repo. [https://github.com/parallella/oh/issues/98](https://github.com/parallella/oh/issues/98)

I have attached bitstream script error log file below:
[bitstream_script_error.txt](https://github.com/eliaskousk/parallella-riscv/files/1063523/bitstream_script_error.txt)

**Comment by eliaskousk** [comment]
Hi @promach,

thank you for reporting this. Another user has already reported me the exact same issue via email. It seems that my port is currently not compatible with Vivado 2017.1 for reasons unknown yet. You need to either build it with the fully tested 2015.4 version of Vivado or retry at a later time, after l manage to re-test and correct such issues on Vivado 2017.1. This could happen sometime during summer, so I recommend that for now, if possible, you just use Vivado 2015.4.

Best regards,
Elias

P.S: For reference this was my complete answer to the other user:

"I cannot reproduce the problem with Vivado 2015.4 which is the version I have installed on my rig and the last version I tested it for GSoC. You can try to open the Vivado project that resides in the 'parallella/fpga/parallella-riscv' directory and see what it says about the bitstream. Does the Vivado project 'think' the bitstream was created? Maybe in this version the bitstream's output path / filename have changed from the assumed 'parallella/fpga/parallella-riscv/system.runs/impl_1/system_wrapper.bit'.

Another possibility is that some strange incompatibility between versions of Vivado (as usual with Xilinx tools) is happening, the design breaks and the 'system_wrapper.bit' bitstream never gets created."

**Comment by buttercutter** [comment]
Ok, in the meanwhile I found out that if I open the project and generate bitstream using GUI vivado, I have the following error:

> [Place 30-415] IO Placement failed due to overutilization. This design contains 439 I/O ports
 while the target  device: 7z010 package: clg400, contains only 230 available user I/O. The target device has 230 usable I/O pins of which 0 are already occupied by user-locked I/Os.
 To rectify this issue:
 1. Ensure you are targeting the correct device and package.  Select a larger device or different package if necessary.
 2. Check the top-level ports of the design to ensure the correct number of ports are specified.
 3. Consider design changes to reduce the number of I/Os necessary.

I suppose parallella-riscv also supports parallella desktop (z7010). 
I am not quite sure what else did I miss.
